# Generated by Django 3.2.3 on 2021-06-19 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0004_photo_privacy'),
        ('user', '0002_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('privacy', models.CharField(choices=[('O', 'Only Me'), ('F', 'Follower Only'), ('P', 'Public')], default='O', max_length=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('photos', models.ManyToManyField(related_name='albums', to='photos.Photo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='user.profile')),
            ],
        ),
    ]
