# Generated by Django 3.2.3 on 2021-07-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_profile_album_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='privacy',
        ),
    ]
