# Generated by Django 3.2.3 on 2021-06-09 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='photos/')),
                ('for_sale', models.BooleanField()),
                ('is_digital', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to='user.profile')),
            ],
        ),
    ]
