# Generated by Django 3.2.3 on 2021-06-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='privacy',
            field=models.CharField(choices=[('O', 'Only Me'), ('F', 'Follower Only'), ('P', 'Public')], default='O', max_length=1),
        ),
    ]
