# Generated by Django 3.2.3 on 2021-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_photos', to='photos.Tag'),
        ),
    ]
