# Generated by Django 3.2.3 on 2021-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20210727_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='optimized',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='optimized_watermarked',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='watermarked',
        ),
        migrations.AddField(
            model_name='photo',
            name='optimized_image',
            field=models.ImageField(blank=True, null=True, upload_to='optimized/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(editable=False, upload_to='photos/'),
        ),
    ]
