# Generated by Django 3.2.3 on 2021-07-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_rename_optimized_image_photo_optimized_image_128'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='optimized_image_1024',
            field=models.ImageField(blank=True, null=True, upload_to='optimized/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='optimized_image_256',
            field=models.ImageField(blank=True, null=True, upload_to='optimized/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='optimized_image_512',
            field=models.ImageField(blank=True, null=True, upload_to='optimized/'),
        ),
    ]
