# Generated by Django 3.2.3 on 2021-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_auto_20210727_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='watermarked_optimized_image_1024',
            field=models.ImageField(blank=True, null=True, upload_to='watermarked_optimized/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='watermarked_optimized_image_128',
            field=models.ImageField(blank=True, null=True, upload_to='watermarked_optimized/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='watermarked_optimized_image_256',
            field=models.ImageField(blank=True, null=True, upload_to='watermarked_optimized/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='watermarked_optimized_image_512',
            field=models.ImageField(blank=True, null=True, upload_to='watermarked_optimized/'),
        ),
    ]
