# Generated by Django 3.2.3 on 2021-07-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210721_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='organizations', to='organizations.OrganizationMember'),
        ),
    ]
