# Generated by Django 3.2.3 on 2021-07-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0010_alter_photo_tags'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibitions', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('for_sale', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='exhibitions.exhibition')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibition_entries', to='photos.photo')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
