# Generated by Django 3.2.3 on 2021-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='exhibition/'),
        ),
    ]
