# Generated by Django 3.2.3 on 2021-07-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_exhibition_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='exhibitionentry',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
