# Generated by Django 3.2.3 on 2021-07-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_auto_20210721_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exhibitionentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
