# Generated by Django 3.2.3 on 2021-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0005_auto_20210725_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=7)),
                ('frame_radius', models.FloatField()),
                ('frame_color', models.CharField(max_length=7)),
                ('frame_padding', models.IntegerField()),
                ('column', models.IntegerField()),
                ('layout', models.CharField(choices=[('G', 'Grid'), ('C', 'Carousel')], max_length=1)),
            ],
        ),
    ]
