# Generated by Django 3.2.3 on 2021-07-25 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0010_alter_photo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=127)),
                ('is_paid', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField(default=orders.models.get_valid_till)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='photos.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
