# Generated by Django 3.2.3 on 2021-07-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='redirection_url',
            field=models.URLField(blank=True),
        ),
    ]
