# Generated by Django 3.2.3 on 2021-07-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_redirection_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='redirection_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
