# Generated by Django 3.2.3 on 2021-07-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_redirection_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='valid_till',
        ),
    ]
